spec-version: 0.36.0

name: aoewif
version: 0.1.0
category: Compilers
license: NONE
github: bokutotu/aoewif

dependencies:
  - base >= 4.22 && < 4.23

language: GHC2024
ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Aoewif.Target.Cuda.Ampere
    - Aoewif.Target.Cuda.Ampere.DSL
    - Aoewif.Target.Cuda.Ampere.Instruction
    - Aoewif.Target.Cuda.Ampere.Render
    - Aoewif.Target.Cuda.Codegen
    - Aoewif.Target.Cuda.DSL
    - Aoewif.Target.Cuda.Syntax
    - Aoewif.Target.Cuda.TensorCoreOp

tests:
  aoewif-test:
    main: Spec.hs
    source-dirs: tests
    default-extensions:
      - MultilineStrings
    dependencies:
      - aoewif
      - hspec
    build-tools:
      - hspec-discover
