spec-version: 0.36.0

name: aoewif
version: 0.1.0
category: Compilers
license: NONE
github: bokutotu/aoewif

dependencies:
  - base >= 4.22 && < 4.23

language: GHC2024
ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Aoewif.Access
    - Aoewif.BufferId
    - Aoewif.Cpu
    - Aoewif.Cpu.Codegen
    - Aoewif.Cpu.IR
    - Aoewif.Cuda
    - Aoewif.Cuda.Codegen
    - Aoewif.Cuda.IR
    - Aoewif.LoopId
    - Aoewif.Name
    - Aoewif.ValueId

tests:
  aoewif-test:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - aoewif
      - hspec
    build-tools:
      - hspec-discover
