module Aoewif.Compute (
    F32,
    Boolean,
    IndexValue,
    Input,
    Output,
    Name (..),
    DataTypeRep,
    f32,
    Tensor,
    Index,
    Expr,
    Reducer,
    Compute,
    BlockM,
    SymbolId (..),
    TensorId (..),
    IndexId (..),
    LoopId (..),
    BlockId (..),
    DimExpr (..),
    Symbol (..),
    DataType (..),
    ComparePredicate (..),
    TensorKind (..),
    TensorDecl (..),
    IndexExpr (..),
    Predicate (..),
    IndexBinding (..),
    Loop (..),
    Block (..),
    Statement (..),
    LoopIR (..),
    IR (..),
    ComputeIndexExpr (..),
    ComputeValueId (..),
    DataExpr (..),
    PredicateExpr (..),
    IndexValueExpr (..),
    ReducerKind (..),
    ComputeStatement (..),
    ComputeBlock (..),
    tensorAt,
    program,
    dim,
    staticDim,
    input,
    output,
    for,
    block,
    load,
    store,
    update,
    add,
    multiply,
    minimumReducer,
    maximumReducer,
    boolean,
    index,
    indexLiteral,
    fma,
    min_,
    max_,
    exp_,
    log_,
    compare_,
    select,
) where

import           Aoewif.Internal.Compute.Block
import           Aoewif.Internal.Compute.Math
import           Aoewif.Internal.Compute.Operation
import           Aoewif.Internal.Compute.State
import           Aoewif.Internal.IR
import           Aoewif.Internal.Primitive         (ComparePredicate (..),
                                                    DataType (..))
